### ISSUE TITLE
IOS 8 以下点击相册崩溃

### ISSUE THREAD

**Issue by JiaqiSun** [ws00801526/XMNPhotoPickerFramework#10]
# define iOS8Later ([UIDevice currentDevice].systemVersion.floatValue >= 10.0f)

直接修改宏 可 见 BUG
XMNPhotoPickerController
- (void)autoPushPhotoCollectionViewController {
  
  if (self.autoPushToPhotoCollection) {
      XMNPhotoCollectionController _photoCollectionC = [[XMNPhotoCollectionController alloc] initWithCollectionViewLayout:[XMNPhotoCollectionController photoCollectionViewLayoutWithWidth:self.view.frame.size.width]];
      __weak typeof(_&self) wSelf = self;
      [[XMNPhotoManager sharedManager] getAlbumsPickingVideoEnable:self.pickingVideoEnable completionBlock:^(NSArray<XMNAlbumModel *> _albums) {
          __weak typeof(_&self) self = wSelf;
          photoCollectionC.album = [albums firstObject];
          [self pushViewController:photoCollectionC animated:NO];   （崩到这一行了） 
      }];
  }
  }

(0x1820badb0 0x18171ff80 0x1872afb80 0x1875976d4 0x1872af144 0x100050f88 0x10005db84 0x18bffd868 0x10024da7c 0x10024da3c 0x1002534e4 0x182070d50 0x18206ebb8 0x181f98c50 0x183880088 0x187282088 0x100071dd8 0x181b368b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ws00801526** [comment]
Hi，已经修复了bug，你可以再试试
