### ISSUE TITLE
添加到pods后，xib资源缺失，而且底部菜单显示不全

### ISSUE THREAD

**Issue by jayshidai** [ws00801526/XMNPhotoPickerFramework#4]
添加到pods后，xib资源缺失，而且底部菜单显示不全。

**Comment by ws00801526** [comment]
Hi.xib文件缺失已经修复,可以更新1.0.1   底部菜单显示不全能提供点详细信息么?  版本,机型

**Comment by jayshidai** [comment]
![image](https://cloud.githubusercontent.com/assets/10294527/14700678/c60b25fa-07d3-11e6-8b51-78c409454348.png)
如果我的导航栏设置为不透明，

-` UINavigationBar *bar = [UINavigationBar appearance];
    bar.tintColor = [UIColor whiteColor];

```
//高度为64
[bar setBackgroundImage:[UIImage imageNamed:@"titleBar"]forBarMetrics:UIBarMetricsDefault];
//设置为不透明
bar.translucent = NO;`我看了一下你的源码，我想了一下，如果要让这种情况显示的话就得改如下地方：#pragma mark - Methods
```
- (void)showAnimated:(BOOL)animated {
  [self.parentController.view addSubview:self];
  if (animated) {
      CGPoint fromPoint = CGPointMake(self.frame.size.width/2, self.contentViewHeight/2 + self.frame.size.height);
      CGPoint toPoint   = CGPointMake(self.frame.size.width/2, self.frame.size.height - self.contentViewHeight/2-64);
      CABasicAnimation *positionAnim = [UIView animationWithFromValue:[NSValue valueWithCGPoint:fromPoint] toValue:[NSValue valueWithCGPoint:toPoint] duration:.2f forKeypath:@"position"];
      [self.contentView.layer addAnimation:positionAnim forKey:nil];
  }
  }

**Comment by ws00801526** [comment]
hi 我不确定 你现在用的这个是不是最新版本,最新版本我已经更改成了用autoLayout 来处理bottomBar的位置了,你可以看下源码

**Comment by jayshidai** [comment]
我已经解决了，我没有改动你的代码，是ios7后导航控制器会向下偏移64px。另外在picker模式中，[XMNPhotoPicker sharePhotoPicker].maxCount=2;你会发现左右移动的图片可以选择三张，而从相册选取则是正确的。你可以检查一下。

**Comment by ws00801526** [comment]
非常感谢,已修复
